[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Configuración de compilador Solidity
solc = "0.8.20"
evm_version = "paris"

# Optimizaciones del compilador
optimizer = true
optimizer_runs = 200

# Configuración de testing
verbosity = 2

# Configuración de gas
gas_limit = 9223372036854775807
gas_price = 20000000000

# Configuración de RPC para desarrollo local
[rpc_endpoints]
local = "http://localhost:8545"

# Configuración para etherscan (no usado en local, pero útil para testnets)
[etherscan]
# No aplicable para Anvil local

# Profile para variables de entorno de deployment
[profile.env]
# Estas se pueden sobrescribir con .env
ANVIL_RPC_URL = "http://localhost:8545"
DEPLOYER_PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"