[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Configuraci贸n de compilador Solidity
solc = "0.8.20"
evm_version = "paris"

# Optimizaciones del compilador
optimizer = true
optimizer_runs = 200

# Configuraci贸n de testing
verbosity = 2

# Configuraci贸n de gas
gas_limit = 9223372036854775807
gas_price = 20000000000

# Configuraci贸n de RPC para desarrollo local
[rpc_endpoints]
local = "http://localhost:8545"